/**
 * Build a CareerUnderstandingV1 from a V2 onboarding profile snapshot.
 *
 * The V1 sections (Retune's Understanding, Best Angles, Evidence, Resume Fuel)
 * expect a CareerUnderstandingV1. When a user has only V2 onboarding data
 * (and no AI-generated understanding document yet), we need to derive that
 * shape from V2 data so the existing UI populates properly with real values
 * instead of empty placeholders.
 *
 * This is a deterministic mapping. Once a real understanding is generated by
 * the background job (Stage 9 -> generateUnderstandingDocument), it replaces
 * this derived version.
 */

import { emptyCareerUnderstanding } from "./schema";
import type {
  CareerUnderstandingV1,
  EvidenceRef,
  EvidenceSignal,
  PositioningOption,
  ResumeFuelItem,
} from "./types";
import type { V2ProfileSnapshot } from "@/lib/onboarding-v2/repository";

function ref(id: string, profilePath: string, label: string, source: EvidenceRef["source"] = "resume"): EvidenceRef {
  return { id, profilePath, label, source };
}

function buildHeadline(p: V2ProfileSnapshot["profile"]): string {
  const parts: string[] = [];
  if (p.confirmed_seniority) parts.push(p.confirmed_seniority);
  if (p.confirmed_role_family) parts.push(p.confirmed_role_family);
  if (p.confirmed_industry) parts.push(`in ${p.confirmed_industry}`);
  if (parts.length === 0) return p.target_role ?? "Career profile in progress";
  return parts.join(" ");
}

function buildNarrative(snapshot: V2ProfileSnapshot): string {
  const p = snapshot.profile;
  if (p.understanding_document) return p.understanding_document;
  if (p.inferred_summary) return p.inferred_summary;
  // Last-resort fallback: stitch together a short narrative from facts
  const company = snapshot.experience[0]?.company;
  const title = snapshot.experience[0]?.title;
  const skills = snapshot.skills.raw_list.slice(0, 4).join(", ");
  const sentences: string[] = [];
  if (title && company) sentences.push(`${title} at ${company}.`);
  if (skills) sentences.push(`Core skills include ${skills}.`);
  if (p.resume_frame) sentences.push(p.resume_frame);
  return sentences.join(" ") || "We are still building your interpretation. Generate the first read to see how Retune understands your career.";
}

function buildPositioningOptions(snapshot: V2ProfileSnapshot): PositioningOption[] {
  const p = snapshot.profile;
  const options: PositioningOption[] = [];

  // PRIMARY — derived from confirmed role_family + target_role + resume_frame
  if (p.target_role || p.confirmed_role_family) {
    options.push({
      id: "primary",
      kind: "primary",
      title: p.target_role ?? p.confirmed_role_family ?? "Primary positioning",
      description: p.resume_frame ?? `Lead with your strongest signal as a ${p.confirmed_role_family ?? "professional"}.`,
      bestFor: p.target_role_specificity
        ? [p.target_role_specificity]
        : p.confirmed_industry
          ? [`${p.confirmed_industry} roles`]
          : ["Roles aligned with your background"],
      emphasize: snapshot.skills.raw_list.slice(0, 3),
      deEmphasize: Array.isArray(p.deemphasis_preferences)
        ? (p.deemphasis_preferences as string[]).slice(0, 3)
        : [],
      risks: [],
      evidenceRefs: [
        ref("primary-target", "profile.target_role", `Targeting ${p.target_role ?? p.confirmed_role_family}`, "user"),
      ],
      userDecision: "accepted",
    });
  }

  // ALTERNATIVE — adjacent role family or industry pivot
  if (p.confirmed_role_family) {
    options.push({
      id: "alternative",
      kind: "alternative",
      title: deriveAdjacentRole(p.confirmed_role_family),
      description: `An adjacent angle that highlights different facets of your background.`,
      bestFor: ["Roles where the primary angle feels too specific"],
      emphasize: snapshot.skills.raw_list.slice(3, 6),
      deEmphasize: [],
      risks: ["May understate your specialised expertise"],
      evidenceRefs: [],
      userDecision: "undecided",
    });
  }

  // STRETCH — seniority+1 or career_transition
  if (p.confirmed_seniority || p.career_transition_detected) {
    options.push({
      id: "stretch",
      kind: "stretch",
      title: deriveStretchRole(p.confirmed_seniority, p.confirmed_role_family),
      description: p.career_transition_detected
        ? "Aspirational angle for the direction you're moving toward."
        : "A higher-scope role you could grow into with the right framing.",
      bestFor: ["Aspirational applications"],
      emphasize: [],
      deEmphasize: [],
      risks: ["May be too forward-leaning for some recruiters"],
      evidenceRefs: [],
      userDecision: "undecided",
    });
  }

  return options;
}

function deriveAdjacentRole(roleFamily: string): string {
  const map: Record<string, string> = {
    "Backend Engineering": "Platform Engineering",
    "Frontend Engineering": "Design Engineering",
    "Fullstack Engineering": "Product Engineering",
    "Data Engineering": "Analytics Engineering",
    "ML Engineering": "Applied AI Engineering",
    "DevOps/SRE": "Platform Infrastructure",
    "Mobile Engineering": "Cross-platform Engineering",
    "Engineering Management": "Technical Lead",
  };
  return map[roleFamily] ?? `Adjacent ${roleFamily}`;
}

function deriveStretchRole(seniority: string | null, roleFamily: string | null): string {
  if (!seniority || !roleFamily) return "Stretch role";
  const next: Record<string, string> = {
    "Entry Level": "Junior",
    "Junior": "Mid-level",
    "Mid-level": "Senior IC",
    "Senior IC": "Staff/Principal IC",
    "Staff/Principal IC": "Engineering Lead",
    "Engineering Lead": "Engineering Manager",
    "Engineering Manager": "Senior Manager",
    "Senior Manager": "Director+",
  };
  const upgraded = next[seniority] ?? seniority;
  return `${upgraded} ${roleFamily}`;
}

function buildEvidenceMap(snapshot: V2ProfileSnapshot) {
  const strongestSignals: EvidenceSignal[] = [];
  const supportingSignals: EvidenceSignal[] = [];
  const weakSignals: EvidenceSignal[] = [];
  const inferredUnconfirmed: EvidenceSignal[] = [];

  // Strongest: experience entries with quantified bullets
  snapshot.experience.forEach((exp, i) => {
    if (!exp.title || !exp.company) return;
    const hasMetrics = (exp.bullets ?? []).some((b) => /\d+%|\d+x|\$\d|\d+M|\d+K/i.test(b));
    if (hasMetrics) {
      strongestSignals.push({
        id: `exp-${i}`,
        label: `${exp.title} at ${exp.company}`,
        interpretation: "Quantified achievements provide strong signal for resume generation.",
        strength: "strong",
        sourceRefs: [ref(`exp-${i}-ref`, `experience[${i}]`, exp.company)],
      });
    } else {
      supportingSignals.push({
        id: `exp-${i}`,
        label: `${exp.title} at ${exp.company}`,
        interpretation: "Role provides context but lacks quantified outcomes.",
        strength: "medium",
        sourceRefs: [ref(`exp-${i}-ref`, `experience[${i}]`, exp.company)],
      });
    }
  });

  // Strongest: top skills
  if (snapshot.skills.raw_list.length > 0) {
    strongestSignals.push({
      id: "skills-core",
      label: `${snapshot.skills.raw_list.length} skills tagged`,
      interpretation: snapshot.skills.raw_list.slice(0, 5).join(", "),
      strength: "strong",
      sourceRefs: [ref("skills-ref", "skills.raw_list", "Skills")],
    });
  }

  // Supporting: education
  snapshot.education.forEach((edu, i) => {
    if (!edu.institution) return;
    supportingSignals.push({
      id: `edu-${i}`,
      label: `${edu.degree ?? "Degree"} — ${edu.institution}`,
      interpretation: edu.field ? `Specialised in ${edu.field}.` : "Academic foundation.",
      strength: "medium",
      sourceRefs: [ref(`edu-${i}-ref`, `education[${i}]`, edu.institution)],
    });
  });

  // Supporting: certifications
  snapshot.certifications.forEach((cert, i) => {
    if (!cert.name) return;
    supportingSignals.push({
      id: `cert-${i}`,
      label: cert.name,
      interpretation: cert.issuer ? `Issued by ${cert.issuer}` : "Certification on file.",
      strength: "medium",
      sourceRefs: [ref(`cert-${i}-ref`, `certifications[${i}]`, cert.name)],
    });
  });

  // Weak: missing critical fields
  const missing = snapshot.metadata?.needs_review_fields ?? [];
  for (const field of missing) {
    weakSignals.push({
      id: `weak-${field}`,
      label: field.replace(/_/g, " "),
      interpretation: "Flagged for review during onboarding audit.",
      strength: "weak",
      sourceRefs: [],
    });
  }
  if (!snapshot.profile.target_role) {
    weakSignals.push({
      id: "weak-target",
      label: "Target role not set",
      interpretation: "Resume generation needs a clear target role.",
      strength: "weak",
      sourceRefs: [],
    });
  }
  if (!snapshot.experience.some((e) => (e.bullets ?? []).some((b) => /\d/.test(b)))) {
    weakSignals.push({
      id: "weak-metrics",
      label: "No quantified achievements",
      interpretation: "Specific numbers significantly improve resume quality.",
      strength: "weak",
      sourceRefs: [],
    });
  }

  // Inferred: AI-derived fields not yet confirmed by user
  const sources = snapshot.metadata?.field_sources ?? {};
  for (const [field, source] of Object.entries(sources)) {
    if (source === "inferred" || source === "ai_inferred") {
      inferredUnconfirmed.push({
        id: `inferred-${field}`,
        label: field.replace(/_/g, " "),
        interpretation: "Inferred from your profile — not yet confirmed.",
        strength: "weak",
        sourceRefs: [],
      });
    }
  }
  if (snapshot.profile.confirmed_industry && !sources.confirmed_industry) {
    inferredUnconfirmed.push({
      id: "inferred-industry",
      label: `Industry: ${snapshot.profile.confirmed_industry}`,
      interpretation: "Inferred from your work history.",
      strength: "medium",
      sourceRefs: [],
    });
  }

  return { strongestSignals, supportingSignals, weakSignals, inferredUnconfirmed };
}

function buildResumeFuel(snapshot: V2ProfileSnapshot) {
  const ready: ResumeFuelItem[] = [];
  const needsSharpening: ResumeFuelItem[] = [];
  const risks: ResumeFuelItem[] = [];
  const suggestedNextEdits: ResumeFuelItem[] = [];

  if (snapshot.experience.length > 0) {
    ready.push({
      id: "ready-experience",
      label: `${snapshot.experience.length} role${snapshot.experience.length === 1 ? "" : "s"} on file`,
      whyItMatters: "Roles, scope, and timeline are ready for resume generation.",
      section: "experience",
      severity: "info",
      sourceRefs: [],
    });
  }
  if (snapshot.skills.raw_list.length > 0) {
    ready.push({
      id: "ready-skills",
      label: `${snapshot.skills.raw_list.length} skills tagged`,
      whyItMatters: "Skills are confirmed and ready to anchor resume keywords.",
      section: "skills",
      severity: "info",
      sourceRefs: [],
    });
  }
  if (snapshot.education.length > 0) {
    ready.push({
      id: "ready-education",
      label: "Education present",
      whyItMatters: "Academic background is captured.",
      section: "education",
      severity: "info",
      sourceRefs: [],
    });
  }
  if (snapshot.projects.length > 0) {
    ready.push({
      id: "ready-projects",
      label: `${snapshot.projects.length} project${snapshot.projects.length === 1 ? "" : "s"}`,
      whyItMatters: "Projects can be selected for tailored resumes.",
      section: "projects",
      severity: "info",
      sourceRefs: [],
    });
  }

  // Needs sharpening: voice profile low confidence
  if (snapshot.voice?.voice_profile_confidence === "low" || snapshot.voice?.voice_profile_source === "default") {
    needsSharpening.push({
      id: "sharpen-voice",
      label: "Writing voice not yet calibrated",
      whyItMatters: "Generated resumes will use defaults until you complete the voice profile.",
      section: "writing_preferences",
      severity: "warning",
      sourceRefs: [],
    });
  }
  if (!snapshot.profile.resume_frame) {
    needsSharpening.push({
      id: "sharpen-frame",
      label: "Resume frame not set",
      whyItMatters: "The single most important takeaway is missing — generation will be generic without it.",
      section: "writing_preferences",
      severity: "warning",
      sourceRefs: [],
    });
  }
  if (!snapshot.experience.some((e) => (e.bullets ?? []).some((b) => /\d/.test(b)))) {
    needsSharpening.push({
      id: "sharpen-metrics",
      label: "No quantified achievements",
      whyItMatters: "Numbers and outcomes dramatically improve resume callback rates.",
      section: "experience",
      severity: "warning",
      sourceRefs: [],
    });
  }

  // Risks: correction unresolved, profile_depth shallow
  if (snapshot.metadata?.correction_unresolved) {
    risks.push({
      id: "risk-corrections",
      label: "Unresolved corrections",
      whyItMatters: "Some onboarding corrections were not fully resolved — review before generating.",
      section: "writing_preferences",
      severity: "warning",
      sourceRefs: [],
    });
  }
  if (snapshot.profile.profile_depth === "shallow") {
    risks.push({
      id: "risk-shallow",
      label: "Profile depth is shallow",
      whyItMatters: "Generated resumes will be limited by the available material.",
      section: "experience",
      severity: "warning",
      sourceRefs: [],
    });
  }
  if (snapshot.profile.resume_stale) {
    risks.push({
      id: "risk-stale",
      label: "Resume may be out of date",
      whyItMatters: "Most recent role ended over 18 months ago — add anything recent before generating.",
      section: "experience",
      severity: "warning",
      sourceRefs: [],
    });
  }

  // Suggested edits
  const score = snapshot.profile.profile_quality_score ?? 0;
  if (score < 80) {
    if (!snapshot.experience.some((e) => (e.bullets ?? []).some((b) => /\d/.test(b)))) {
      suggestedNextEdits.push({
        id: "edit-metrics",
        label: "Add 2 measurable achievements",
        whyItMatters: "Even rough numbers (team size, scale, impact %) will lift the quality score.",
        section: "experience",
        severity: "info",
        sourceRefs: [],
      });
    }
    if (!snapshot.profile.target_role_specificity) {
      suggestedNextEdits.push({
        id: "edit-specificity",
        label: "Sharpen target role specificity",
        whyItMatters: "More specific targeting produces more focused resume content.",
        section: "writing_preferences",
        severity: "info",
        sourceRefs: [],
      });
    }
    if (snapshot.voice?.voice_profile_source === "default") {
      suggestedNextEdits.push({
        id: "edit-voice",
        label: "Complete your voice profile",
        whyItMatters: "Resumes will sound more like you with a calibrated voice.",
        section: "writing_preferences",
        severity: "info",
        sourceRefs: [],
      });
    }
  }

  return { ready, needsSharpening, risks, suggestedNextEdits };
}

/**
 * Build a CareerUnderstandingV1 from V2 onboarding data. Used as the
 * fallback when no AI-generated understanding exists yet but the user has
 * completed onboarding.
 */
export function buildUnderstandingFromV2(
  v2: V2ProfileSnapshot,
  userId: string,
): CareerUnderstandingV1 {
  const empty = emptyCareerUnderstanding({ userId });
  const headline = buildHeadline(v2.profile);
  const narrative = buildNarrative(v2);
  const positioningOptions = buildPositioningOptions(v2);
  const evidenceMap = buildEvidenceMap(v2);
  const resumeFuel = buildResumeFuel(v2);

  return {
    ...empty,
    summary: {
      headline,
      narrative,
      confidenceLabel:
        (v2.profile.profile_quality_score ?? 0) >= 80
          ? "high"
          : (v2.profile.profile_quality_score ?? 0) >= 60
            ? "medium"
            : "low",
      caveats: [],
      sourceRefs: [],
      confirmed: false,
    },
    positioning: {
      selectedId: positioningOptions[0]?.id ?? null,
      options: positioningOptions,
    },
    evidenceMap,
    resumeFuel,
  };
}
