/**
 * Seed semantic memory.
 *
 * Stub knowledge graph used by the comprehension specialists in commit #2.
 * Tiny on purpose — just enough to validate the cognitive cycle end-to-end
 * with a TitleSchemaRetriever and CompanySchemaRetriever.
 *
 * Migrated to KuzuDB and `packages/ontology/data/*.json` in commit #4
 * when the ontology package lands. Until then this module is the source
 * of truth for the limited set of roles and companies the workbench can
 * reason about.
 *
 */

export interface RoleNode {
  canonical_id: string;
  display_name: string;
  aliases: readonly string[];
  family: string;
  level: "intern" | "junior" | "mid" | "senior" | "staff" | "principal" | "manager" | "director";
  yoe_band: readonly [number, number];
  archetype?: string;
}

export interface CompanyNode {
  canonical_id: string;
  display_name: string;
  aliases: readonly string[];
  domain?: string;
  hq_country: string;
  funding_stage?: string;
  tier: "big_tech" | "unicorn" | "scale_up" | "series_b" | "early" | "public";
  industries: readonly string[];
  /** 8-dim cultural fingerprint vector. */
  cultural_fingerprint: readonly [number, number, number, number, number, number, number, number];
}

// ─────────────── Role catalog ───────────────
//
// Just enough to cover the seed eval cases (backend SWE, frontend, ML).

export const SEED_ROLES: readonly RoleNode[] = [
  {
    canonical_id: "role.swe.junior",
    display_name: "Junior Software Engineer",
    aliases: [
      "junior software engineer",
      "associate software engineer",
      "swe i",
      "software engineer i",
      "entry-level software engineer",
      "new grad software engineer",
    ],
    family: "swe",
    level: "junior",
    yoe_band: [0, 2],
  },
  {
    canonical_id: "role.swe.mid",
    display_name: "Software Engineer",
    aliases: ["software engineer", "swe", "software engineer ii", "swe ii"],
    family: "swe",
    level: "mid",
    yoe_band: [2, 5],
  },
  {
    canonical_id: "role.swe.senior",
    display_name: "Senior Software Engineer",
    aliases: [
      "senior software engineer",
      "sr software engineer",
      "sr. swe",
      "swe iii",
      "senior swe",
    ],
    family: "swe",
    level: "senior",
    yoe_band: [5, 8],
  },
  {
    canonical_id: "role.swe.staff",
    display_name: "Staff Software Engineer",
    aliases: ["staff software engineer", "staff swe", "staff engineer"],
    family: "swe",
    level: "staff",
    yoe_band: [8, 12],
  },
  {
    canonical_id: "role.frontend.junior",
    display_name: "Junior Frontend Engineer",
    aliases: [
      "junior frontend engineer",
      "associate frontend engineer",
      "junior frontend developer",
    ],
    family: "frontend",
    level: "junior",
    yoe_band: [0, 2],
  },
  {
    canonical_id: "role.frontend.mid",
    display_name: "Frontend Engineer",
    aliases: ["frontend engineer", "frontend developer", "ui engineer"],
    family: "frontend",
    level: "mid",
    yoe_band: [2, 5],
  },
  {
    canonical_id: "role.ml.senior",
    display_name: "Senior ML Engineer",
    aliases: [
      "senior ml engineer",
      "senior machine learning engineer",
      "sr ml engineer",
      "senior mle",
    ],
    family: "ml_engineering",
    level: "senior",
    yoe_band: [5, 8],
    archetype: "scaled_it",
  },
  {
    canonical_id: "role.ml.staff",
    display_name: "Staff ML Engineer",
    aliases: ["staff ml engineer", "staff machine learning engineer", "staff mle"],
    family: "ml_engineering",
    level: "staff",
    yoe_band: [8, 12],
  },

  // ── Data / ML ──────────────────────────────────────────────────
  {
    canonical_id: "role.data_science.mid",
    display_name: "Data Scientist",
    aliases: [
      "data scientist",
      "data science engineer",
      "applied scientist",
      "research scientist",
      "quantitative analyst",
    ],
    family: "data_science",
    level: "mid",
    yoe_band: [2, 5],
  },
  {
    canonical_id: "role.ml.mid",
    display_name: "ML Engineer",
    aliases: [
      "ml engineer",
      "machine learning engineer",
      "mle",
      "ai engineer",
      "applied ml engineer",
      "machine learning software engineer",
    ],
    family: "ml_engineering",
    level: "mid",
    yoe_band: [2, 5],
  },
  {
    canonical_id: "role.data_engineering.mid",
    display_name: "Data Engineer",
    aliases: [
      "data engineer",
      "analytics engineer",
      "data platform engineer",
      "data infrastructure engineer",
    ],
    family: "data_engineering",
    level: "mid",
    yoe_band: [2, 5],
  },

  // ── Product ────────────────────────────────────────────────────
  {
    canonical_id: "role.pm.mid",
    display_name: "Product Manager",
    aliases: [
      "product manager",
      "pm",
      "associate product manager",
      "associate pm",
      "apm",
      "technical product manager",
      "tpm",
    ],
    family: "product",
    level: "mid",
    yoe_band: [2, 5],
  },
  {
    canonical_id: "role.pm.senior",
    display_name: "Senior Product Manager",
    aliases: [
      "senior product manager",
      "senior pm",
      "sr product manager",
      "sr. product manager",
      "sr pm",
    ],
    family: "product",
    level: "senior",
    yoe_band: [5, 8],
  },

  // ── Frontend ───────────────────────────────────────────────────
  {
    canonical_id: "role.frontend.senior",
    display_name: "Senior Frontend Engineer",
    aliases: [
      "senior frontend engineer",
      "senior frontend developer",
      "sr frontend engineer",
      "sr. frontend engineer",
      "senior react engineer",
      "senior react developer",
      "react developer",
      "ui engineer",
      "web developer",
      "senior web developer",
      "senior ui engineer",
    ],
    family: "frontend",
    level: "senior",
    yoe_band: [5, 8],
  },

  // ── Backend ────────────────────────────────────────────────────
  {
    canonical_id: "role.backend.mid",
    display_name: "Backend Engineer",
    aliases: [
      "backend engineer",
      "backend developer",
      "api engineer",
      "server-side engineer",
      "server side engineer",
    ],
    family: "backend",
    level: "mid",
    yoe_band: [2, 5],
  },
  {
    canonical_id: "role.backend.senior",
    display_name: "Senior Backend Engineer",
    aliases: [
      "senior backend engineer",
      "senior backend developer",
      "sr backend engineer",
      "sr. backend engineer",
      "senior api engineer",
    ],
    family: "backend",
    level: "senior",
    yoe_band: [5, 8],
  },

  // ── Full Stack ─────────────────────────────────────────────────
  {
    canonical_id: "role.fullstack.mid",
    display_name: "Full Stack Engineer",
    aliases: [
      "full stack engineer",
      "full stack developer",
      "fullstack engineer",
      "fullstack developer",
      "full-stack engineer",
      "full-stack developer",
      "software engineer full stack",
    ],
    family: "fullstack",
    level: "mid",
    yoe_band: [2, 5],
  },
  {
    canonical_id: "role.fullstack.senior",
    display_name: "Senior Full Stack Engineer",
    aliases: [
      "senior full stack engineer",
      "senior full stack developer",
      "senior fullstack engineer",
      "senior fullstack developer",
      "sr full stack engineer",
      "sr. full stack engineer",
    ],
    family: "fullstack",
    level: "senior",
    yoe_band: [5, 8],
  },

  // ── DevOps / Infra ─────────────────────────────────────────────
  {
    canonical_id: "role.devops.mid",
    display_name: "DevOps Engineer",
    aliases: [
      "devops engineer",
      "site reliability engineer",
      "sre",
      "platform engineer",
      "infrastructure engineer",
      "cloud engineer",
      "infra engineer",
      "reliability engineer",
    ],
    family: "infrastructure",
    level: "mid",
    yoe_band: [2, 5],
  },
  {
    canonical_id: "role.devops.senior",
    display_name: "Senior DevOps Engineer",
    aliases: [
      "senior devops engineer",
      "senior site reliability engineer",
      "senior sre",
      "senior platform engineer",
      "senior infrastructure engineer",
      "senior cloud engineer",
      "sr devops engineer",
      "sr. sre",
    ],
    family: "infrastructure",
    level: "senior",
    yoe_band: [5, 8],
  },

  // ── Engineering Management ─────────────────────────────────────
  {
    canonical_id: "role.em.mid",
    display_name: "Engineering Manager",
    aliases: [
      "engineering manager",
      "em",
      "tech lead",
      "technical lead",
      "team lead",
      "lead software engineer",
      "tech lead manager",
    ],
    family: "management",
    level: "manager",
    yoe_band: [6, 10],
  },
  {
    canonical_id: "role.em.senior",
    display_name: "Senior Engineering Manager",
    aliases: [
      "senior engineering manager",
      "senior em",
      "director of engineering",
      "head of engineering",
    ],
    family: "management",
    level: "director",
    yoe_band: [8, 15],
  },

  // ── Principal / Distinguished ──────────────────────────────────
  {
    canonical_id: "role.swe.principal",
    display_name: "Principal Engineer",
    aliases: [
      "principal engineer",
      "principal software engineer",
      "distinguished engineer",
      "fellow",
      "senior principal engineer",
    ],
    family: "swe",
    level: "principal",
    yoe_band: [12, 20],
  },
];

// ─────────────── Company catalog ───────────────

export const SEED_COMPANIES: readonly CompanyNode[] = [
  {
    canonical_id: "company.stripe",
    display_name: "Stripe",
    aliases: ["stripe", "stripe inc", "stripe payments", "stripe.com"],
    domain: "stripe.com",
    hq_country: "US",
    funding_stage: "late_stage_private",
    tier: "unicorn",
    industries: ["fintech", "payments"],
    cultural_fingerprint: [0.9, 0.85, 0.4, 0.7, 0.95, 0.8, 0.6, 0.7],
  },
  {
    canonical_id: "company.cloudflare",
    display_name: "Cloudflare",
    aliases: ["cloudflare", "cloudflare inc", "cloudflare.com", "cf"],
    domain: "cloudflare.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["infrastructure", "security", "cdn"],
    cultural_fingerprint: [0.85, 0.8, 0.5, 0.65, 0.9, 0.7, 0.55, 0.65],
  },
  {
    canonical_id: "company.pinterest",
    display_name: "Pinterest",
    aliases: ["pinterest", "pinterest inc"],
    domain: "pinterest.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["consumer", "social"],
    cultural_fingerprint: [0.75, 0.7, 0.6, 0.55, 0.7, 0.6, 0.7, 0.6],
  },
  {
    canonical_id: "company.doordash",
    display_name: "DoorDash",
    aliases: ["doordash", "doordash inc"],
    domain: "doordash.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["delivery", "marketplaces"],
    cultural_fingerprint: [0.8, 0.75, 0.45, 0.6, 0.85, 0.7, 0.6, 0.55],
  },
  {
    canonical_id: "company.monzo",
    display_name: "Monzo",
    aliases: ["monzo", "monzo bank"],
    domain: "monzo.com",
    hq_country: "UK",
    funding_stage: "late_stage_private",
    tier: "unicorn",
    industries: ["fintech", "banking"],
    cultural_fingerprint: [0.7, 0.85, 0.7, 0.5, 0.75, 0.6, 0.75, 0.6],
  },
  {
    canonical_id: "company.octopus_energy",
    display_name: "Octopus Energy",
    aliases: ["octopus energy", "octopus"],
    domain: "octopus.energy",
    hq_country: "UK",
    funding_stage: "late_stage_private",
    tier: "unicorn",
    industries: ["energy", "consumer_utilities"],
    cultural_fingerprint: [0.65, 0.75, 0.75, 0.5, 0.7, 0.6, 0.8, 0.55],
  },
  {
    canonical_id: "company.helio",
    display_name: "Helio",
    aliases: ["helio", "helio finance"],
    hq_country: "US",
    funding_stage: "series_b",
    tier: "series_b",
    industries: ["fintech", "payments"],
    cultural_fingerprint: [0.75, 0.7, 0.5, 0.6, 0.8, 0.7, 0.6, 0.55],
  },
  {
    canonical_id: "company.threadly",
    display_name: "Threadly",
    aliases: ["threadly"],
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["consumer", "social"],
    cultural_fingerprint: [0.78, 0.72, 0.55, 0.6, 0.75, 0.65, 0.65, 0.6],
  },

  // ── Major tech companies ───────────────────────────────────────
  {
    canonical_id: "company.intercom",
    display_name: "Intercom",
    aliases: ["intercom", "intercom inc", "intercom.com"],
    domain: "intercom.com",
    hq_country: "US",
    funding_stage: "late_stage_private",
    tier: "unicorn",
    industries: ["saas", "customer_support", "messaging"],
    cultural_fingerprint: [0.8, 0.82, 0.55, 0.65, 0.85, 0.7, 0.6, 0.65],
  },
  {
    canonical_id: "company.shopify",
    display_name: "Shopify",
    aliases: ["shopify", "shopify inc"],
    domain: "shopify.com",
    hq_country: "CA",
    funding_stage: "public",
    tier: "public",
    industries: ["ecommerce", "saas", "payments"],
    cultural_fingerprint: [0.82, 0.8, 0.6, 0.65, 0.85, 0.72, 0.65, 0.68],
  },
  {
    canonical_id: "company.airbnb",
    display_name: "Airbnb",
    aliases: ["airbnb", "airbnb inc"],
    domain: "airbnb.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["travel", "marketplaces", "consumer"],
    cultural_fingerprint: [0.78, 0.82, 0.7, 0.6, 0.8, 0.7, 0.72, 0.65],
  },
  {
    canonical_id: "company.uber",
    display_name: "Uber",
    aliases: ["uber", "uber technologies", "uber tech"],
    domain: "uber.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["rideshare", "delivery", "marketplaces"],
    cultural_fingerprint: [0.82, 0.78, 0.45, 0.65, 0.88, 0.75, 0.58, 0.62],
  },
  {
    canonical_id: "company.meta",
    display_name: "Meta",
    aliases: ["meta", "facebook", "meta platforms", "meta inc", "fb"],
    domain: "meta.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "big_tech",
    industries: ["social", "advertising", "consumer", "vr"],
    cultural_fingerprint: [0.88, 0.85, 0.42, 0.72, 0.95, 0.82, 0.5, 0.75],
  },
  {
    canonical_id: "company.apple",
    display_name: "Apple",
    aliases: ["apple", "apple inc"],
    domain: "apple.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "big_tech",
    industries: ["consumer_hardware", "software", "services"],
    cultural_fingerprint: [0.95, 0.9, 0.35, 0.8, 0.92, 0.88, 0.45, 0.82],
  },
  {
    canonical_id: "company.microsoft",
    display_name: "Microsoft",
    aliases: ["microsoft", "microsoft corp", "msft"],
    domain: "microsoft.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "big_tech",
    industries: ["enterprise_software", "cloud", "productivity", "gaming"],
    cultural_fingerprint: [0.88, 0.82, 0.5, 0.75, 0.88, 0.8, 0.6, 0.78],
  },
  {
    canonical_id: "company.amazon",
    display_name: "Amazon",
    aliases: ["amazon", "amazon.com", "aws", "amazon web services", "amazon inc"],
    domain: "amazon.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "big_tech",
    industries: ["ecommerce", "cloud", "logistics", "enterprise_software"],
    cultural_fingerprint: [0.9, 0.85, 0.38, 0.78, 0.95, 0.85, 0.5, 0.8],
  },
  {
    canonical_id: "company.netflix",
    display_name: "Netflix",
    aliases: ["netflix", "netflix inc"],
    domain: "netflix.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["streaming", "entertainment", "consumer"],
    cultural_fingerprint: [0.88, 0.85, 0.5, 0.72, 0.9, 0.8, 0.55, 0.72],
  },
  {
    canonical_id: "company.linkedin",
    display_name: "LinkedIn",
    aliases: ["linkedin", "linkedin inc"],
    domain: "linkedin.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "big_tech",
    industries: ["professional_network", "saas", "advertising"],
    cultural_fingerprint: [0.85, 0.8, 0.55, 0.7, 0.88, 0.78, 0.62, 0.72],
  },
  {
    canonical_id: "company.salesforce",
    display_name: "Salesforce",
    aliases: ["salesforce", "salesforce.com", "sfdc"],
    domain: "salesforce.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["saas", "crm", "enterprise_software"],
    cultural_fingerprint: [0.82, 0.78, 0.58, 0.68, 0.85, 0.75, 0.65, 0.7],
  },
  {
    canonical_id: "company.atlassian",
    display_name: "Atlassian",
    aliases: ["atlassian", "atlassian corp"],
    domain: "atlassian.com",
    hq_country: "AU",
    funding_stage: "public",
    tier: "public",
    industries: ["saas", "developer_tools", "collaboration"],
    cultural_fingerprint: [0.8, 0.85, 0.68, 0.62, 0.82, 0.72, 0.72, 0.68],
  },
  {
    canonical_id: "company.github",
    display_name: "GitHub",
    aliases: ["github", "github inc"],
    domain: "github.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "big_tech",
    industries: ["developer_tools", "saas", "vcs"],
    cultural_fingerprint: [0.85, 0.88, 0.62, 0.65, 0.88, 0.78, 0.68, 0.72],
  },
  {
    canonical_id: "company.gitlab",
    display_name: "GitLab",
    aliases: ["gitlab", "gitlab inc"],
    domain: "gitlab.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["developer_tools", "saas", "devops"],
    cultural_fingerprint: [0.82, 0.85, 0.72, 0.62, 0.85, 0.75, 0.7, 0.68],
  },
  {
    canonical_id: "company.figma",
    display_name: "Figma",
    aliases: ["figma", "figma inc"],
    domain: "figma.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["design_tools", "saas", "collaboration"],
    cultural_fingerprint: [0.85, 0.88, 0.65, 0.65, 0.88, 0.8, 0.7, 0.72],
  },
  {
    canonical_id: "company.notion",
    display_name: "Notion",
    aliases: ["notion", "notion labs", "notion.so"],
    domain: "notion.so",
    hq_country: "US",
    funding_stage: "late_stage_private",
    tier: "unicorn",
    industries: ["productivity", "saas", "collaboration"],
    cultural_fingerprint: [0.82, 0.85, 0.7, 0.62, 0.85, 0.75, 0.72, 0.68],
  },
  {
    canonical_id: "company.linear",
    display_name: "Linear",
    aliases: ["linear", "linear app", "linear.app"],
    domain: "linear.app",
    hq_country: "US",
    funding_stage: "series_b",
    tier: "series_b",
    industries: ["developer_tools", "saas", "project_management"],
    cultural_fingerprint: [0.88, 0.9, 0.65, 0.62, 0.88, 0.82, 0.65, 0.72],
  },
  {
    canonical_id: "company.vercel",
    display_name: "Vercel",
    aliases: ["vercel", "vercel inc"],
    domain: "vercel.com",
    hq_country: "US",
    funding_stage: "late_stage_private",
    tier: "unicorn",
    industries: ["developer_tools", "infrastructure", "saas"],
    cultural_fingerprint: [0.88, 0.9, 0.62, 0.65, 0.9, 0.82, 0.65, 0.72],
  },
  {
    canonical_id: "company.datadog",
    display_name: "Datadog",
    aliases: ["datadog", "datadog inc"],
    domain: "datadoghq.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["observability", "infrastructure", "saas"],
    cultural_fingerprint: [0.85, 0.82, 0.48, 0.68, 0.9, 0.78, 0.55, 0.7],
  },
  {
    canonical_id: "company.snowflake",
    display_name: "Snowflake",
    aliases: ["snowflake", "snowflake inc"],
    domain: "snowflake.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["data_platform", "cloud", "saas"],
    cultural_fingerprint: [0.85, 0.82, 0.5, 0.68, 0.88, 0.78, 0.58, 0.72],
  },
  {
    canonical_id: "company.databricks",
    display_name: "Databricks",
    aliases: ["databricks", "databricks inc"],
    domain: "databricks.com",
    hq_country: "US",
    funding_stage: "late_stage_private",
    tier: "unicorn",
    industries: ["data_platform", "ml_platform", "saas"],
    cultural_fingerprint: [0.88, 0.85, 0.52, 0.7, 0.9, 0.8, 0.58, 0.72],
  },
  {
    canonical_id: "company.hubspot",
    display_name: "HubSpot",
    aliases: ["hubspot", "hubspot inc"],
    domain: "hubspot.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["saas", "crm", "marketing"],
    cultural_fingerprint: [0.78, 0.8, 0.62, 0.62, 0.82, 0.72, 0.68, 0.65],
  },
  {
    canonical_id: "company.zendesk",
    display_name: "Zendesk",
    aliases: ["zendesk", "zendesk inc"],
    domain: "zendesk.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["saas", "customer_support", "crm"],
    cultural_fingerprint: [0.78, 0.78, 0.6, 0.62, 0.82, 0.72, 0.65, 0.65],
  },
  {
    canonical_id: "company.twilio",
    display_name: "Twilio",
    aliases: ["twilio", "twilio inc", "twilio sendgrid", "sendgrid"],
    domain: "twilio.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["saas", "communications", "developer_tools"],
    cultural_fingerprint: [0.82, 0.8, 0.55, 0.65, 0.85, 0.75, 0.6, 0.68],
  },
  {
    canonical_id: "company.auth0",
    display_name: "Auth0",
    aliases: ["auth0", "auth0 inc", "okta", "okta inc"],
    domain: "auth0.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["saas", "security", "identity"],
    cultural_fingerprint: [0.82, 0.8, 0.52, 0.65, 0.85, 0.75, 0.58, 0.68],
  },
  {
    canonical_id: "company.pagerduty",
    display_name: "PagerDuty",
    aliases: ["pagerduty", "pagerduty inc"],
    domain: "pagerduty.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["saas", "devops", "observability"],
    cultural_fingerprint: [0.8, 0.78, 0.52, 0.62, 0.85, 0.75, 0.58, 0.65],
  },
  {
    canonical_id: "company.elastic",
    display_name: "Elastic",
    aliases: ["elastic", "elasticsearch", "elastic nv"],
    domain: "elastic.co",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["saas", "search", "observability"],
    cultural_fingerprint: [0.82, 0.82, 0.55, 0.65, 0.85, 0.75, 0.6, 0.68],
  },
  {
    canonical_id: "company.hashicorp",
    display_name: "HashiCorp",
    aliases: ["hashicorp", "hashicorp inc"],
    domain: "hashicorp.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["developer_tools", "infrastructure", "saas"],
    cultural_fingerprint: [0.85, 0.85, 0.58, 0.65, 0.88, 0.78, 0.62, 0.7],
  },
  {
    canonical_id: "company.confluent",
    display_name: "Confluent",
    aliases: ["confluent", "confluent inc"],
    domain: "confluent.io",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["data_streaming", "infrastructure", "saas"],
    cultural_fingerprint: [0.85, 0.82, 0.5, 0.68, 0.88, 0.78, 0.58, 0.7],
  },
  {
    canonical_id: "company.mongodb",
    display_name: "MongoDB",
    aliases: ["mongodb", "mongodb inc"],
    domain: "mongodb.com",
    hq_country: "US",
    funding_stage: "public",
    tier: "public",
    industries: ["database", "saas", "developer_tools"],
    cultural_fingerprint: [0.82, 0.8, 0.55, 0.65, 0.85, 0.75, 0.6, 0.68],
  },
  {
    canonical_id: "company.canva",
    display_name: "Canva",
    aliases: ["canva", "canva pty ltd", "canva.com"],
    domain: "canva.com",
    hq_country: "AU",
    funding_stage: "late_stage_private",
    tier: "unicorn",
    industries: ["design_tools", "saas", "consumer"],
    cultural_fingerprint: [0.82, 0.85, 0.68, 0.62, 0.85, 0.75, 0.7, 0.68],
  },
  {
    canonical_id: "company.openai",
    display_name: "OpenAI",
    aliases: ["openai", "open ai"],
    domain: "openai.com",
    hq_country: "US",
    funding_stage: "late_stage_private",
    tier: "unicorn",
    industries: ["ai", "ml_platform", "saas"],
    cultural_fingerprint: [0.92, 0.9, 0.55, 0.72, 0.95, 0.85, 0.58, 0.78],
  },
];
