# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ml_pb2 as ml__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLStub(object):
    """─────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/retune.ml.v1.ML/Health',
                request_serializer=ml__pb2.HealthRequest.SerializeToString,
                response_deserializer=ml__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Embed = channel.unary_unary(
                '/retune.ml.v1.ML/Embed',
                request_serializer=ml__pb2.EmbedRequest.SerializeToString,
                response_deserializer=ml__pb2.EmbedResponse.FromString,
                _registered_method=True)
        self.ExtractSpans = channel.unary_unary(
                '/retune.ml.v1.ML/ExtractSpans',
                request_serializer=ml__pb2.ExtractSpansRequest.SerializeToString,
                response_deserializer=ml__pb2.ExtractSpansResponse.FromString,
                _registered_method=True)
        self.ClassifyDiscourse = channel.unary_unary(
                '/retune.ml.v1.ML/ClassifyDiscourse',
                request_serializer=ml__pb2.ClassifyDiscourseRequest.SerializeToString,
                response_deserializer=ml__pb2.ClassifyDiscourseResponse.FromString,
                _registered_method=True)
        self.DetectContradiction = channel.unary_unary(
                '/retune.ml.v1.ML/DetectContradiction',
                request_serializer=ml__pb2.NLIRequest.SerializeToString,
                response_deserializer=ml__pb2.NLIResponse.FromString,
                _registered_method=True)
        self.SimulateReader = channel.unary_unary(
                '/retune.ml.v1.ML/SimulateReader',
                request_serializer=ml__pb2.ReaderSimRequest.SerializeToString,
                response_deserializer=ml__pb2.ReaderSimResponse.FromString,
                _registered_method=True)
        self.ProposeArcs = channel.unary_unary(
                '/retune.ml.v1.ML/ProposeArcs',
                request_serializer=ml__pb2.ProposeArcsRequest.SerializeToString,
                response_deserializer=ml__pb2.ProposeArcsResponse.FromString,
                _registered_method=True)
        self.SolveEvidence = channel.unary_unary(
                '/retune.ml.v1.ML/SolveEvidence',
                request_serializer=ml__pb2.SolveEvidenceRequest.SerializeToString,
                response_deserializer=ml__pb2.SolveEvidenceResponse.FromString,
                _registered_method=True)
        self.ComposeBullet = channel.unary_unary(
                '/retune.ml.v1.ML/ComposeBullet',
                request_serializer=ml__pb2.ComposeBulletRequest.SerializeToString,
                response_deserializer=ml__pb2.ComposeBulletResponse.FromString,
                _registered_method=True)
        self.Critique = channel.unary_unary(
                '/retune.ml.v1.ML/Critique',
                request_serializer=ml__pb2.CritiqueRequest.SerializeToString,
                response_deserializer=ml__pb2.CritiqueResponse.FromString,
                _registered_method=True)
        self.PredictOutcome = channel.unary_unary(
                '/retune.ml.v1.ML/PredictOutcome',
                request_serializer=ml__pb2.PredictOutcomeRequest.SerializeToString,
                response_deserializer=ml__pb2.PredictOutcomeResponse.FromString,
                _registered_method=True)
        self.AuditFairness = channel.unary_unary(
                '/retune.ml.v1.ML/AuditFairness',
                request_serializer=ml__pb2.AuditFairnessRequest.SerializeToString,
                response_deserializer=ml__pb2.AuditFairnessResponse.FromString,
                _registered_method=True)
        self.SimulateATS = channel.unary_unary(
                '/retune.ml.v1.ML/SimulateATS',
                request_serializer=ml__pb2.SimulateATSRequest.SerializeToString,
                response_deserializer=ml__pb2.SimulateATSResponse.FromString,
                _registered_method=True)


class MLServicer(object):
    """─────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────

    """

    def Health(self, request, context):
        """Sensory layer (V1, fusiform, Wernicke's)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractSpans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyDiscourse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectContradiction(self, request, context):
        """Comprehension layer (Wernicke's, ACC)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulateReader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProposeArcs(self, request, context):
        """Strategy layer (DLPFC, default mode network)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SolveEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComposeBullet(self, request, context):
        """Production layer (Broca's, premotor)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Critique(self, request, context):
        """Critique + decision (TPJ, vmPFC)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictOutcome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuditFairness(self, request, context):
        """Fairness (regulatory + ACC)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulateATS(self, request, context):
        """ATS vendor simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ml__pb2.HealthRequest.FromString,
                    response_serializer=ml__pb2.HealthResponse.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=ml__pb2.EmbedRequest.FromString,
                    response_serializer=ml__pb2.EmbedResponse.SerializeToString,
            ),
            'ExtractSpans': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractSpans,
                    request_deserializer=ml__pb2.ExtractSpansRequest.FromString,
                    response_serializer=ml__pb2.ExtractSpansResponse.SerializeToString,
            ),
            'ClassifyDiscourse': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyDiscourse,
                    request_deserializer=ml__pb2.ClassifyDiscourseRequest.FromString,
                    response_serializer=ml__pb2.ClassifyDiscourseResponse.SerializeToString,
            ),
            'DetectContradiction': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectContradiction,
                    request_deserializer=ml__pb2.NLIRequest.FromString,
                    response_serializer=ml__pb2.NLIResponse.SerializeToString,
            ),
            'SimulateReader': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateReader,
                    request_deserializer=ml__pb2.ReaderSimRequest.FromString,
                    response_serializer=ml__pb2.ReaderSimResponse.SerializeToString,
            ),
            'ProposeArcs': grpc.unary_unary_rpc_method_handler(
                    servicer.ProposeArcs,
                    request_deserializer=ml__pb2.ProposeArcsRequest.FromString,
                    response_serializer=ml__pb2.ProposeArcsResponse.SerializeToString,
            ),
            'SolveEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.SolveEvidence,
                    request_deserializer=ml__pb2.SolveEvidenceRequest.FromString,
                    response_serializer=ml__pb2.SolveEvidenceResponse.SerializeToString,
            ),
            'ComposeBullet': grpc.unary_unary_rpc_method_handler(
                    servicer.ComposeBullet,
                    request_deserializer=ml__pb2.ComposeBulletRequest.FromString,
                    response_serializer=ml__pb2.ComposeBulletResponse.SerializeToString,
            ),
            'Critique': grpc.unary_unary_rpc_method_handler(
                    servicer.Critique,
                    request_deserializer=ml__pb2.CritiqueRequest.FromString,
                    response_serializer=ml__pb2.CritiqueResponse.SerializeToString,
            ),
            'PredictOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictOutcome,
                    request_deserializer=ml__pb2.PredictOutcomeRequest.FromString,
                    response_serializer=ml__pb2.PredictOutcomeResponse.SerializeToString,
            ),
            'AuditFairness': grpc.unary_unary_rpc_method_handler(
                    servicer.AuditFairness,
                    request_deserializer=ml__pb2.AuditFairnessRequest.FromString,
                    response_serializer=ml__pb2.AuditFairnessResponse.SerializeToString,
            ),
            'SimulateATS': grpc.unary_unary_rpc_method_handler(
                    servicer.SimulateATS,
                    request_deserializer=ml__pb2.SimulateATSRequest.FromString,
                    response_serializer=ml__pb2.SimulateATSResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'retune.ml.v1.ML', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('retune.ml.v1.ML', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ML(object):
    """─────────────────────────────────────────────────────────────
    Service
    ─────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retune.ml.v1.ML/Health',
            ml__pb2.HealthRequest.SerializeToString,
            ml__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retune.ml.v1.ML/Embed',
            ml__pb2.EmbedRequest.SerializeToString,
            ml__pb2.EmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractSpans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retune.ml.v1.ML/ExtractSpans',
            ml__pb2.ExtractSpansRequest.SerializeToString,
            ml__pb2.ExtractSpansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyDiscourse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retune.ml.v1.ML/ClassifyDiscourse',
            ml__pb2.ClassifyDiscourseRequest.SerializeToString,
            ml__pb2.ClassifyDiscourseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectContradiction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retune.ml.v1.ML/DetectContradiction',
            ml__pb2.NLIRequest.SerializeToString,
            ml__pb2.NLIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimulateReader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retune.ml.v1.ML/SimulateReader',
            ml__pb2.ReaderSimRequest.SerializeToString,
            ml__pb2.ReaderSimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProposeArcs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retune.ml.v1.ML/ProposeArcs',
            ml__pb2.ProposeArcsRequest.SerializeToString,
            ml__pb2.ProposeArcsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SolveEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retune.ml.v1.ML/SolveEvidence',
            ml__pb2.SolveEvidenceRequest.SerializeToString,
            ml__pb2.SolveEvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComposeBullet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retune.ml.v1.ML/ComposeBullet',
            ml__pb2.ComposeBulletRequest.SerializeToString,
            ml__pb2.ComposeBulletResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Critique(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retune.ml.v1.ML/Critique',
            ml__pb2.CritiqueRequest.SerializeToString,
            ml__pb2.CritiqueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retune.ml.v1.ML/PredictOutcome',
            ml__pb2.PredictOutcomeRequest.SerializeToString,
            ml__pb2.PredictOutcomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuditFairness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retune.ml.v1.ML/AuditFairness',
            ml__pb2.AuditFairnessRequest.SerializeToString,
            ml__pb2.AuditFairnessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimulateATS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retune.ml.v1.ML/SimulateATS',
            ml__pb2.SimulateATSRequest.SerializeToString,
            ml__pb2.SimulateATSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
