import { z } from "zod";
import { EDUCATION_STATUSES, EXPERIENCE_LEVELS } from "../enums";

export const skillSchema = z.object({
  name: z.string().max(100),
  evidence: z.string().max(500).optional(),
  years: z.number().min(0).max(80).optional(),
});

export const experienceSchema = z.object({
  company: z.string().max(200),
  title: z.string().max(200),
  titleForResume: z.string().max(200).optional(),
  startDate: z.string().max(20).optional(),
  endDate: z.string().max(20).optional(),
  description: z.string().max(5000).optional(),
  metrics: z.array(z.object({
    metric: z.string().max(200).optional(),
    value: z.string().max(200).optional(),
    context: z.string().max(500).optional(),
    direction: z.string().max(100).optional(),
  })).max(30).optional(),
  tools: z.array(z.string().max(100)).max(100).optional(),
  teamSize: z.number().min(0).max(100000).optional(),
  client: z.string().max(200).optional(),
  industry: z.string().max(200).optional(),
});

export const educationSchema = z.object({
  degree: z.string().max(200),
  institution: z.string().max(200),
  startDate: z.string().max(20).optional(),
  endDate: z.string().max(20).optional(),
  status: z.enum(EDUCATION_STATUSES).optional(),
  coursework: z.array(z.string().max(200)).max(100).optional(),
  capstone: z.string().max(500).optional(),
});

export const projectSchema = z.object({
  name: z.string().max(200).optional(),
  type: z.string().max(100).optional(),
  year: z.number().min(1900).max(2200).optional(),
  description: z.string().max(5000).optional(),
  technologies: z.array(z.string().max(100)).max(100).optional(),
  role: z.string().max(200).optional(),
  keyMetric: z.string().max(500).optional(),
  context: z.string().max(500).optional(),
  tools: z.array(z.string().max(100)).max(100).optional(),
  outcome: z.string().max(500).optional(),
});

export const profileSchema = z.object({
  fullName: z.string().max(100).default(""),
  email: z.string().email().or(z.literal("")) .default(""),
  phone: z.string().max(30).nullable().optional(),
  linkedin: z.string().max(200).nullable().optional(),
  github: z.string().max(200).nullable().optional(),
  portfolio: z.string().max(200).nullable().optional(),
  website: z.string().max(200).nullable().optional(),
  location: z.string().max(200).default(""),
  visaStatus: z.string().max(100).nullable().optional(),
  currentTitle: z.string().max(100).nullable().optional(),
  yearsOfExperience: z.number().min(0).max(80).nullable().optional(),
  professionalSummary: z.string().max(5000).optional(),
  summarySignals: z.array(z.string().max(300)).max(50).default([]),
  domainExperience: z.array(z.string().max(100)).max(50).default([]),
  careerHighlights: z.array(z.string().max(500)).max(50).default([]),
  relocationPreferences: z.array(z.string().max(100)).max(20).default([]),
  targetRoles: z.array(z.string().max(100)).max(20).default([]),
  experienceLevel: z.enum(EXPERIENCE_LEVELS).default("mid"),
  experience: z.array(experienceSchema).max(30).default([]),
  education: z.array(educationSchema).max(20).default([]),
  certifications: z.array(z.string().max(200)).max(50).default([]),
  projects: z.array(projectSchema).max(50).default([]),
  languages: z.array(z.string().max(100)).max(50).default([]),
  awards: z.array(z.string().max(200)).max(50).default([]),
  publications: z.array(z.string().max(300)).max(50).default([]),
  volunteering: z.array(z.string().max(300)).max(50).default([]),
  skillsTier1: z.array(skillSchema).max(50).default([]),
  skillsTier2: z.array(skillSchema).max(50).default([]),
  skillsTier3: z.array(skillSchema).max(50).default([]),
  technicalSkills: z.array(z.string().max(100)).max(100).default([]),
  tools: z.array(z.string().max(100)).max(100).default([]),
  professionalSkills: z.array(z.string().max(100)).max(100).default([]),
  methodologies: z.array(z.string().max(100)).max(100).default([]),
  softSkills: z.array(z.string().max(100)).max(100).default([]),
  domainSkills: z.array(z.string().max(100)).max(100).default([]),
  voiceNotes: z.string().max(5000).nullable().optional(),
  summary: z.string().max(5000).optional(),
  profileMarkdown: z.string().max(20000).optional(),
  // Career intent
  interestedRoles: z.array(z.string().max(100)).max(20).default([]),
  careerDirection: z.enum(["same", "slight_shift", "major_switch", "not_sure", ""]).default(""),
  preferredMarkets: z.array(z.string().max(100)).max(20).default([]),
  workPreference: z.enum(["remote", "hybrid", "onsite", "open", ""]).default(""),
  seniorityComfort: z.array(z.string().max(100)).max(20).default([]),
  industriesOfInterest: z.array(z.string().max(100)).max(30).default([]),
  roleDealbreakers: z.array(z.string().max(200)).max(20).default([]),
  // Resume writing preferences
  toneSignals: z.array(z.string().max(100)).max(20).default([]),
  styleConstraints: z.array(z.string().max(200)).max(20).default([]),
  emphasisAreas: z.array(z.string().max(200)).max(20).default([]),
  deEmphasisAreas: z.array(z.string().max(200)).max(20).default([]),
});

export const patchProfileSchema = profileSchema.partial();

export const openAiProfileJsonSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    fullName: { type: "string", description: "Candidate's full legal name as on resume." },
    email: { type: "string", description: "Email address. Empty string if not present." },
    phone: { type: ["string", "null"], description: "Phone number including country code. Null if not present." },
    linkedin: { type: ["string", "null"], description: "LinkedIn profile URL. Null if not present." },
    github: { type: ["string", "null"], description: "GitHub profile URL. Null if not present." },
    portfolio: { type: ["string", "null"], description: "Portfolio or personal website URL. Null if not present." },
    website: { type: ["string", "null"], description: "Any other website URL. Null if not present." },
    location: { type: "string", description: "City, state/country. Empty string if not present." },
    visaStatus: { type: ["string", "null"], description: "Visa or work authorization status if mentioned. Null if not present." },
    currentTitle: { type: ["string", "null"], description: "Most recent job title. Null if not present." },
    yearsOfExperience: { type: ["number", "null"], description: "Total years of professional experience. Null if not determinable." },
    experienceLevel: { type: "string", enum: [...EXPERIENCE_LEVELS], description: "Inferred seniority: entry, early, mid, senior, or staff." },
    professionalSummary: { type: ["string", "null"], description: "Professional summary or objective statement from resume. Null if absent." },
    summarySignals: { type: "array", items: { type: "string" }, description: "Key professional signals: specializations, notable achievements, domain expertise." },
    domainExperience: { type: "array", items: { type: "string" }, description: "Industry domains worked in (e.g. fintech, healthcare, e-commerce)." },
    careerHighlights: { type: "array", items: { type: "string" }, description: "Top 3-5 career achievements with quantified impact." },
    relocationPreferences: { type: "array", items: { type: "string" } },
    targetRoles: { type: "array", items: { type: "string" }, description: "Target roles if explicitly stated or strongly implied by resume objective." },
    experience: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          company: { type: "string", description: "Company or organization name." },
          title: { type: "string", description: "Job title as written on resume." },
          titleForResume: { type: ["string", "null"], description: "Optimized title for resume if different from original. Null if same." },
          startDate: { type: "string", description: "Start date. Month YYYY when month known, otherwise YYYY. Empty string if unknown." },
          endDate: { type: "string", description: "End date. Month YYYY, or empty string if current/ongoing." },
          description: { type: "string", description: "Full role description with newline-separated bullets." },
          metrics: {
            type: "array",
            description: "Quantified achievements: percentages, counts, dollar amounts, time spans.",
            items: {
              type: "object",
              additionalProperties: false,
              properties: {
                metric: { type: "string", description: "What was measured (e.g. latency, revenue, team size)." },
                value: { type: "string", description: "The numeric value with unit (e.g. 40%, $2M, 5 engineers)." },
                context: { type: "string", description: "Brief context for the metric." },
                direction: { type: "string", description: "Direction of change: increase, decrease, or empty." },
              },
              required: ["metric", "value", "context", "direction"],
            },
          },
          tools: { type: "array", items: { type: "string" }, description: "Technologies and tools used in this role." },
          skills: { type: "array", items: { type: "string" }, description: "Skills demonstrated in this role." },
          teamSize: { type: ["number", "null"], description: "Number of people managed or team size. Null if not mentioned." },
          client: { type: ["string", "null"], description: "Client name if consulting/agency role. Null otherwise." },
          industry: { type: ["string", "null"], description: "Industry sector. Null if not determinable." },
          domain: { type: ["string", "null"], description: "Technical domain (e.g. backend, ML, infrastructure). Null if unclear." },
          achievements: { type: "array", items: { type: "string" }, description: "Bullet-point achievements with concrete results." },
        },
        required: [
          "company",
          "title",
          "titleForResume",
          "startDate",
          "endDate",
          "description",
          "metrics",
          "tools",
          "skills",
          "teamSize",
          "client",
          "industry",
          "domain",
          "achievements",
        ],
      },
    },
    education: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          degree: { type: "string", description: "Degree type and name (e.g. B.S. Computer Science)." },
          institution: { type: "string", description: "University or school name." },
          startDate: { type: "string", description: "Start date. YYYY or Month YYYY. Empty if unknown." },
          endDate: { type: "string", description: "End/graduation date. YYYY or Month YYYY. Empty if ongoing." },
          status: { type: "string" },
          coursework: { type: "array", items: { type: "string" } },
          capstone: { type: ["string", "null"], description: "Thesis or capstone project title. Null if none." },
          fieldOfStudy: { type: "string" },
          grade: { type: ["string", "null"], description: "GPA or grade. Null if not listed." },
        },
        required: ["degree", "institution", "startDate", "endDate", "status", "coursework", "capstone", "fieldOfStudy", "grade"],
      },
    },
    certifications: { type: "array", items: { type: "string" } },
    projects: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          name: { type: "string", description: "Project name or title." },
          type: { type: "string" },
          year: { type: ["number", "null"], description: "Year of the project. Null if unknown." },
          description: { type: "string" },
          technologies: { type: "array", items: { type: "string" } },
          techStack: { type: "array", items: { type: "string" } },
          role: { type: ["string", "null"], description: "Role in the project. Null if not specified." },
          keyMetric: { type: "string" },
          impact: { type: "string" },
          link: { type: ["string", "null"], description: "URL to project. Null if not provided." },
        },
        required: ["name", "type", "year", "description", "technologies", "techStack", "role", "keyMetric", "impact", "link"],
      },
    },
    languages: { type: "array", items: { type: "string" } },
    awards: { type: "array", items: { type: "string" } },
    publications: { type: "array", items: { type: "string" } },
    volunteering: { type: "array", items: { type: "string" } },
    technicalSkills: { type: "array", items: { type: "string" }, description: "Programming languages, frameworks, libraries (e.g. Python, Java, Spring Boot, React). Do NOT include tools/platforms/methodologies here." },
    tools: { type: "array", items: { type: "string" }, description: "Vendor products, platforms, IDEs, CI/CD systems (e.g. AWS, Docker, Jira, Power BI). Do NOT include programming languages or methodologies here." },
    professionalSkills: { type: "array", items: { type: "string" }, description: "Business / role-specific capabilities (e.g. Stakeholder Management, Requirements Gathering, UAT). Do NOT include technical skills or soft skills here." },
    methodologies: { type: "array", items: { type: "string" }, description: "Process frameworks (e.g. Agile, Scrum, TDD, Kanban). Do NOT include tools or technical skills here." },
    softSkills: { type: "array", items: { type: "string" }, description: "Interpersonal traits (e.g. Leadership, Communication, Mentoring). Do NOT include technical or professional skills here." },
    domainSkills: { type: "array", items: { type: "string" }, description: "Industry / domain knowledge (e.g. fintech, healthcare, payments). Do NOT include technical or professional skills here." },
    skillsTier1: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          name: { type: "string" },
          evidence: { type: "string" },
          years: { type: "number" },
        },
        required: ["name", "evidence", "years"],
      },
    },
    skillsTier2: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          name: { type: "string" },
          evidence: { type: "string" },
          years: { type: "number" },
        },
        required: ["name", "evidence", "years"],
      },
    },
    skillsTier3: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          name: { type: "string" },
          evidence: { type: "string" },
          years: { type: "number" },
        },
        required: ["name", "evidence", "years"],
      },
    },
    summary: { type: ["string", "null"], description: "Resume summary or objective text. Null if absent." },
    voiceNotes: { type: ["string", "null"], description: "Any voice/tone notes about the candidate's writing style. Null if none." },
  },
  required: [
    "fullName",
    "email",
    "phone",
    "linkedin",
    "github",
    "portfolio",
    "website",
    "location",
    "visaStatus",
    "currentTitle",
    "yearsOfExperience",
    "experienceLevel",
    "professionalSummary",
    "summarySignals",
    "domainExperience",
    "careerHighlights",
    "relocationPreferences",
    "targetRoles",
    "experience",
    "education",
    "certifications",
    "projects",
    "languages",
    "awards",
    "publications",
    "volunteering",
    "technicalSkills",
    "tools",
    "professionalSkills",
    "methodologies",
    "softSkills",
    "domainSkills",
    "skillsTier1",
    "skillsTier2",
    "skillsTier3",
    "summary",
    "voiceNotes",
  ],
} as const;
